config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "/contact", to: "pages#contact"
  get "/about", to: "pages#about"
  get "/trade-in", to: "pages#trade-in"

  resources :makes, only: [:show, :index] do
    resources :models, only: [:show] do
      resources :cars, only: [:show]
    end
  end
  resources :cars, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :model, foreign_key: "model_id"
  belongs_to :make, foreign_key: "make_id"
  validates  :mileage, presence: true
  validates :year, presence: true
end

app/models/make.rb
class Make < ApplicationRecord
  has_many :models
  has_many :cars, through: :models
end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :make
  has_many :cars
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Cars.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
    @model = Model.find(params[:model_id])
  end

  def create
    @car = Car.new(car_params)
    if car.save
      redirect_to car_path(@car), notice: "Car has been made"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(car_params)
      redirect_to car_path(@car), notice: "Car was updated"
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def car_params
    params.require(:car).permit(:name, :model_id, :make_id, :year, :mileage, :photo)
  end
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  def index
    @makes = Make.all
  end

  def show
    @make = Make.find(params[:id])
    @models = @make.models.where(make_id: @make)
  end

  def new
    @make = Make.new
  end

  def create
    @make = Make.new(make_params)
    if @make.save!
      redirect_to make_path(@make), notice: "Make has been made"
    else
      render :new
    end
  end

  def destroy
    @make.destroy
  end

  private

  def make_params
    params.require(:make).permit(:name)
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  def index
    @model = Model.all
  end

  def show
    @model = Model.find(params[:id])
    # @cars = @models.cars.where(model_id: @model)

  end

  def new
    @model = Model.new
    @make = Make.find(params[:make_id])
  end

  def create
    @model = Model.new(model_params)
    if @model.save!
      redirect_to model_path(@model), notice: "Model has been made"
    else
      render :new
    end
  end

  def destroy
    @model.destroy
  end

  private
  def model_params
    params.require(:model).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/makes/index.html.erb
<div class="main">
  <% @makes.each do |make| %>
  <div class="make-card">
    <li><%= link_to make_path(make) do %>
      <%= make.name %></li>
      <% end %>
    <% end %>
  </div>
</div>

app/views/makes/show.html.erb
<%= @make.name %>

<% @models.each do |model|%>
<li><%= link_to make_model_path(model) do %>
    <%= model.name %></li>
    <% end %>
  <% end %>

app/views/pages/home.html.erb
<div class="big">
  <div class="home-banner">

    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media2.giphy.com/media/sDCma70RplcNG/giphy.gif?cid=790b76115cae1b5b77666357491c0f7a);">
      <div class="container">
        <h1>ZPC <strong>Motors</strong>!</h1>
        <p>High qulity second hand vehicles. The only <strong>JEVIC</strong> certified cars in mauritius! </p>
        <a class="btn btn-flat" href="#">Search</a>
        <i class="far fa-arrow-alt-circle-down fa-4x" class="dev-page-btn" onclick="scrollToBottom()"></i>
      </div>
    </div>

  </div>

  <div class="mid-box" id="content">
    <div class="mid-left">
      <div class="mid-left-info">
        <h1>Trade in your car</h1>
        <p><span id="banner-typed-text"></span></p>
      </div>
      <div class="mid-left-carousel">
        <!-- <div class="carousel">
          <a class="carousel-item" href="#one!"><img src="https://lorempixel.com/250/250/nature/1"></a>
          <a class="carousel-item" href="#two!"><img src="https://lorempixel.com/250/250/nature/2"></a>
          <a class="carousel-item" href="#three!"><img src="https://lorempixel.com/250/250/nature/3"></a>
          <a class="carousel-item" href="#four!"><img src="https://lorempixel.com/250/250/nature/4"></a>
          <a class="carousel-item" href="#five!"><img src="https://lorempixel.com/250/250/nature/5"></a>
        </div> -->
      </div>
    </div>
    <div class="mid-right">
      <div class="right-top">
        <%= link_to makes_path do %>
          <p>Car Makes</p>
          <% end %>
      </div>
      <div class="right-mid">
        Right Middle
      </div>
      <div class="right-bottom">
        Right Bottom
      </div>
    </div>
  </div>
</div>


<script>
var elmnt = document.getElementById("content");


function scrollToBottom() {
  elmnt.scrollIntoView({behavior: "smooth"}); // Bottom
}
</script>

<!-- <script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.carousel');
    var instances = M.Carousel.init(elems, options);
  });
</script>
 -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>